(defun kill-ring-save-to-file()
  (with-temp-file "~/.emacs.d/inits/09-kill-ring-hist.el"
    (insert "(setq kill-ring '( \n")
    (let (point-start point-end)
      (while (not (equal (car kill-ring) nil))
        (insert "\" ")
        (setq point-start (point))
        (insert (car kill-ring))
        (setq  point-end (point))
        (goto-char point-start)
        (while (not (equal point-end (point)))
          (goto-char (+ (point) 1))
          (when (or(= (following-char) 34) (= (following-char) 92))
            (insert "\\")
            (setq point-end (+ point-end 1))
            )
          )
        (insert "\" \n")
        (setq kill-ring (cdr kill-ring))
        )
      (insert "))\n\n")
      (insert "(setq kill-ring-yank-pointer (nthcdr 0 kill-ring))")
      )
    )
  )
(add-hook 'kill-emacs-hook 'kill-ring-save-to-file)

